config/routes.rb
Rails.application.routes.draw do

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :categories, only: [:index, :show]
  resources :features, only: [:index, :show]
  resources :products, only: [:index]
  resources :users, only: [:show]

  root to: "static_pages#home"

  get 'home', to: "static_pages#home", as: "home"

  get 'signup', to: "users#new", as: "signup"

  post 'signup', to: "users#create"

  get 'login', to: "sessions#new", as: "login"

  post 'login', to: "sessions#create"

  delete "logout", to: "sessions#destroy", as: "logout"

  get 'about', to: "static_pages#about", as: "about"

  get 'help', to: "static_pages#help", as: "help"

  get 'contact', to: "static_pages#contact", as: "contact"

  post 'toggle_feature/:id', to: "users#toggle_feature", as: "toggle_feature"

  get 'cart/:id', to: 'users#cart', as: 'cart'

end

app/models/user.rb
class User < ApplicationRecord
    has_many :list_items, dependent: :destroy
    has_many :features, through: :list_items
    attr_accessor :remember_token
    before_save { email.downcase! }
    validates :first_name, presence: true, length: { maximum: 50 }
    validates :last_name, presence: true, length: { maximum: 50 }
    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
    validates :email, presence: true, length: { maximum: 255 },
                      format: { with: VALID_EMAIL_REGEX },
                      uniqueness: { case_sensitive: false }
    has_secure_password
    validates :password, presence: true, length: { minimum: 6 }, unless: :guest?

    # Returns the hash digest of the given string.
    def self.digest(string)
        cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                      BCrypt::Engine.cost
        BCrypt::Password.create(string, cost: cost)
    end

    # Returns a random token.
    def self.new_token
        SecureRandom.urlsafe_base64
    end

    # Make a remember_token to preserve user login between sessions
    def remember
        self.remember_token = User.new_token
        update_attribute(:remember_digest, User.digest(remember_token))
    end

    # Returns true if the given token matches the digest.
    def authenticated?(remember_token)
        return false if remember_digest.nil?
        BCrypt::Password.new(remember_digest).is_password?(remember_token)
    end

    # Forgets a user.
    def forget
        update_attribute(:remember_digest, nil)
    end

    def move_to(user)
        features.update_all(user_id: user.id)
    end

    def guest?
        email.include?('bogus.com')
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    def index
        @users = User.all
    end

    def new
        @user = User.new
    end

    def create
        @user = params[:user] ? User.new(user_params) : create_new_guest
        if @user.save
            log_in @user
            redirect_to root_url
        else
            render :new
        end
    end

    def show
        @user = User.find(params[:id])
        @features = @user.features
    end

    def cart
        @user = User.find(params[:id])
        @features = @user.features
        @products = []
        @features.each do |feature|
            feature.products.select('products.*, feature_products.additional_info').each do | product |
                @products.push(product)
                puts "product.id = #{product.id}"
            end
        end
        @products = @products.uniq { |p| p.id }
    end

    def toggle_feature
        puts request.path
        @user = User.find(session[:user_id])
        @features = @user.features
        @feature = Feature.find(params[:id])
        if @features.exists?(@feature.id)
            ListItem.where(user_id: @user.id, feature_id: @feature.id).destroy_all
        else
            @features << @feature
        end
    end

    private

    def user_params
        params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation)
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/cart.html.erb
<% provide(:title, "Cart") %>
<h1 class="page-head"><%= @user.first_name %>'s Products</h1>
<h5 class="page-subhead">Amazon Links are often blocked by adblockers. If you are using an adblocker, please disable it and refresh this page to view products.</h5>
<div class="row">
        <% @products.each do |product| %>
        <div id="<%= " product_#{product.id}" %>" class="large-4 medium-6 small-12 columns">
            <div class="amzn-link"><%= product.image_link.html_safe %></div>
            <p class="title"><%= product.text_link.html_safe %></p>
            <p class="info"><%= product.additional_info %></p>
        </div>
        <% end %>
</div>

app/views/users/index.html.erb
<% provide(:title, "Users") %>
<h1 class="page-head">Users List</h1>
<div class="row">
    <% @users.each do |user| %>
        <div id="<%= " user_#{user.id}" %>" class="large-3 medium-4 small-6 columns">
            <p><%= user.first_name %> <%= user.last_name %> </p>
        </div>
    <% end %>
</div>

app/views/users/new.html.erb
<% provide(:title, "Signup") %>
<h1 class="page-head">Signup</h1>

<div class="large-8 large-centered medium-10 medium-centered small-12 small-centered columns">
    <%= form_for(@user, url: signup_path) do |f| %>

    <div class="row">

        <%= render 'shared/error_messages' %>

        <div class="large-5 medium-12 small-12" style="float: left">
            <%= f.label :first_name %>
            <%= f.text_field :first_name, class: 'form-control', required: true %>
        </div>
        <div class="large-5 medium-12 small-12" style="float: right">
            <%= f.label :last_name %>
            <%= f.text_field :last_name, class: 'form-control', required: true %>
        </div>
    </div>

    <%= f.label :email %>
    <%= f.email_field :email, class: 'form-control', required: true %>

    <%= f.label :password %>
    <%= f.password_field :password, class: 'form-control', required: true %>

    <%= f.label :password_confirmation, "Confirm Password" %>
    <%= f.password_field :password_confirmation, class: 'form-control', required: true %>

    <%= f.submit "Create Account", class: "button radius" %>

    <% end %>
</div>
<script>
$("#new_user").validate();
</script>

app/views/users/show.html.erb
<% provide(:title, "My List") %>
<div id="list_head" class="list_head">
    <h1><%= @user.first_name.upcase %>'S FEATURES</h1>
</div>
<div class="row">
    <% @features.each do |feature| %>
    <div id="<%= " feature_#{feature.id}" %>" class="large-4 medium-6 small-12 columns">
        <%= link_to toggle_feature_path(feature.id), method: :post do %>
        <p class="tile">
            <%= feature.description %>
        </p>
        <% end %>
    </div>
    <% end %>
</div>