config/routes.rb
Rails.application.routes.draw do

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :categories, only: [:index, :show]
  resources :features, only: [:index, :show]
  resources :products, only: [:index]
  resources :users, only: [:show]

  root to: "static_pages#home"

  get 'home', to: "static_pages#home", as: "home"

  get 'signup', to: "users#new", as: "signup"

  post 'signup', to: "users#create"

  get 'login', to: "sessions#new", as: "login"

  post 'login', to: "sessions#create"

  delete "logout", to: "sessions#destroy", as: "logout"

  get 'about', to: "static_pages#about", as: "about"

  get 'help', to: "static_pages#help", as: "help"

  get 'contact', to: "static_pages#contact", as: "contact"

  post 'toggle_feature/:id', to: "users#toggle_feature", as: "toggle_feature"

  get 'cart/:id', to: 'users#cart', as: 'cart'

end

app/models/feature.rb
class Feature < ApplicationRecord
     has_many :category_features
     has_many :categories, :through => :category_features
     has_many :feature_products
     has_many :products, :through => :feature_products
     has_many :list_items, dependent: :destroy
     has_many :users, :through => :list_items
end

app/controllers/features_controller.rb
class FeaturesController < ApplicationController
    def index
        @features = Feature.all
    end

    def show
        @feature = Feature.find(params[:id])
        @products = @feature.products.select('products.*, feature_products.additional_info')
    end

    def add_to_list
        puts "Running add_to_list..."
        current_user.list.features << Feature.find(params[:id])
    end
end

app/helpers/features_helper.rb
module FeaturesHelper
end

app/views/features/index.html.erb
<% provide(:title, "Features") %>
<h1 class="page-head">All Features List</h1>
<div class="row">
    <% @features.each do |feature| %>
    <div id="<%= " feature_#{feature.id}" %>" class="large-4 medium-6 small-12 columns">
        <%= link_to feature_path(feature) do %>
        <p class="tile">
            <%= feature.description %>
        </p>
        <% end %>
    </div>
    <% end %>
</div>

app/views/features/show.html.erb
<% provide(:title, "Products") %>
<h1 class="page-head">'<%= @feature.description %>' Products</h1>
<h5 class="page-subhead">Amazon Links are often blocked by adblockers. If you are using an adblocker, please disable it and refresh this page to view products.</h5>
<div class="row">
    <% @products.each do |product| %>
        <div id="<%= " product_#{product.id}" %>" class="large-4 medium-6 small-12 columns">
            <div class="amzn-link"><%= product.image_link.html_safe %></div>
            <p class="title"><%= product.text_link.html_safe %></p>
            <p class="info"><%= product.additional_info %></p>
        </div>
    <% end %>
</div>