config/routes.rb
Rails.application.routes.draw do

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :categories, only: [:index, :show]
  resources :features, only: [:index, :show]
  resources :products, only: [:index]
  resources :users, only: [:show]

  root to: "static_pages#home"

  get 'home', to: "static_pages#home", as: "home"

  get 'signup', to: "users#new", as: "signup"

  post 'signup', to: "users#create"

  get 'login', to: "sessions#new", as: "login"

  post 'login', to: "sessions#create"

  delete "logout", to: "sessions#destroy", as: "logout"

  get 'about', to: "static_pages#about", as: "about"

  get 'help', to: "static_pages#help", as: "help"

  get 'contact', to: "static_pages#contact", as: "contact"

  post 'toggle_feature/:id', to: "users#toggle_feature", as: "toggle_feature"

  get 'cart/:id', to: 'users#cart', as: 'cart'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
    has_many :category_features
    has_many :features, :through => :category_features

    def list_features
        self.features.includes(:category_features).references(:category_features)
    end
end

app/models/category_feature.rb
class CategoryFeature < ApplicationRecord
    belongs_to :feature
    belongs_to :category
end

app/models/feature.rb
class Feature < ApplicationRecord
     has_many :category_features
     has_many :categories, :through => :category_features
     has_many :feature_products
     has_many :products, :through => :feature_products
     has_many :list_items, dependent: :destroy
     has_many :users, :through => :list_items
end

app/models/feature_product.rb
class FeatureProduct < ApplicationRecord
    belongs_to :feature
    belongs_to :product
end

app/models/interested_person.rb
class InterestedPerson < ApplicationRecord
end

app/models/list.rb
class List < ApplicationRecord
    has_many :features
    belongs_to :user
end

app/models/list_item.rb
class ListItem < ApplicationRecord
    belongs_to :user
    belongs_to :feature
end

app/models/list_session.rb
class ListSession < ApplicationRecord
  #Initialize User List Session
  def initialize(session)
      @session = session
      @session[:list] ||= {}
  end

  #List Count
  def list_count
      if (@session[:list][:features] && @session[:list][:features] != {})
          @session[:list][:features].count
      else
          0
      end
  end

  #List Contents
  def list_contents
        features = @session[:list][:features]

        if (features && features != {})

            #Determine Quantities
            quantities = Hash[features.uniq.map {|i| [i, features.count(i)]}]

            #Get features from DB
            features_array = feature.find(features.uniq)

            #Create Qty Array
            features_new = {}
            features_array.each{
                |a| features_new[a] = {"qty" => quantities[a.id.to_s]}
            }

            #Output appended
            return features_new

        end

  end
end

app/models/product.rb
class Product < ApplicationRecord
    has_many :feature_products
    has_many :features, :through => :feature_products
end

app/models/user.rb
class User < ApplicationRecord
    has_many :list_items, dependent: :destroy
    has_many :features, through: :list_items
    attr_accessor :remember_token
    before_save { email.downcase! }
    validates :first_name, presence: true, length: { maximum: 50 }
    validates :last_name, presence: true, length: { maximum: 50 }
    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
    validates :email, presence: true, length: { maximum: 255 },
                      format: { with: VALID_EMAIL_REGEX },
                      uniqueness: { case_sensitive: false }
    has_secure_password
    validates :password, presence: true, length: { minimum: 6 }, unless: :guest?

    # Returns the hash digest of the given string.
    def self.digest(string)
        cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                      BCrypt::Engine.cost
        BCrypt::Password.create(string, cost: cost)
    end

    # Returns a random token.
    def self.new_token
        SecureRandom.urlsafe_base64
    end

    # Make a remember_token to preserve user login between sessions
    def remember
        self.remember_token = User.new_token
        update_attribute(:remember_digest, User.digest(remember_token))
    end

    # Returns true if the given token matches the digest.
    def authenticated?(remember_token)
        return false if remember_digest.nil?
        BCrypt::Password.new(remember_digest).is_password?(remember_token)
    end

    # Forgets a user.
    def forget
        update_attribute(:remember_digest, nil)
    end

    def move_to(user)
        features.update_all(user_id: user.id)
    end

    def guest?
        email.include?('bogus.com')
    end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  def show
      @list = current_list
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/features_helper.rb
module FeaturesHelper
end

app/helpers/lists_helper.rb
module ListsHelper
    def current_list
        @user = session[:user_id]
        if session[:list_id]
            @current_list ||= List.find(session[:list_id])
        elsif session[:list_id].nil?
            @current_list = List.create(user: current_user)
            session[:list_id] = @current_list.id
        end
        @current_list
    end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
    # Logs in the user
    def log_in(user)
        session[:user_id] = user.id
    end

    # Remembers the user when they log in
    def remember(user)
        user.remember
        cookies.permanent.signed[:user_id] = user.id
        cookies.permanent[:remember_token] = user.remember_token
    end

    # Logs out the current user
    def log_out
        forget(current_user)
        session.delete(:user_id)
        @current_user = nil
    end

    # Forgets a persistent session.
    def forget(user)
        user.forget
        cookies.delete(:user_id)
        cookies.delete(:remember_token)
    end

    # Returns the current logged-in user (if any).
    def current_user
        puts "session[:user_id] = #{session[:user_id]}"
        if (user_id = session[:user_id])
            @current_user ||= User.find_by(id: user_id)
        elsif (user_id = cookies.signed[:user_id])
            user = User.find_by(id: user_id)
            if user && user.authenticated?(cookies[:remember_token])
                log_in user
                @current_user = user
            end
        end
    end

    def create_guest_user
        u = User.new(first_name: "Guest", email: "guest_#{Time.now.to_i}#{rand(99)}@bogus.com")
        u.save!(validate: false)
        session[:guest_user_id] = u.id
        u
    end

    # Returns true if the user is logged in, false otherwise.
    def logged_in?
        !current_user.nil? && !current_user.guest?
    end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_footer.html.erb
<div class="footer">
    <h4>©2017 INTELLIHOME</h4>
</div>

app/views/layouts/_header.html.erb
<div class="top-bar">
    <div class="top-bar-title">
        <strong>
            <%= link_to root_url, class:"title-bar-title" do %>
            IntelliHome
            <% end %>
        </strong>
    </div>
    <div id="responsive-menu">
        <div class="top-bar-left">
            <ul class="menu">
                <li>
                    <%= link_to "CATEGORIES", :controller => :categories, :action => :index %>
                </li>
                <li>
                    <%= link_to "POPULAR PRODUCTS", :controller => :products, :action => :index %>
                </li>
            </ul>
        </div>
        <div class="top-bar-right">
            <ul class="menu">
                <li>
                    <% if logged_in? %>
                        <li class="dropdown">
                            <ul class="dropdown menu" data-dropdown-menu>
                                <li>
                                    <%= link_to "LOG OUT", logout_path, method: "delete" %>
                                </li>
                            </ul>
                        </li>
                    <% else %>
                        <%= link_to "LOG IN", login_path %>
                    <% end %>
                </li>
                <li>
                    <%= link_to "MY LIST", current_user %>
                </li>
                <li>
                    <%= link_to "CART", cart_url(current_user) %>
                </li>
            </ul>
        </div>
    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8"/>
        <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
        <meta name="description" content="Solutions-based smart home market place. Choose your features, get your system. IntelliHome" />
        <meta property="og:title" content="The Rock" />
        <meta property="og:type" content="website" />
        <meta property="og:url" content="http://shopintellihome.com" />
        <meta property="og:image" content="https://s3-us-west-1.amazonaws.com/intellihome-hassurunous/images/titletile.png" />

        <title><%= yield(:title) %> | IntelliHome</title>

        <%= stylesheet_link_tag    "application" %>
        <%= javascript_include_tag "application", 'data-turbolinks-track' => true %>
        <%= csrf_meta_tags %>
        <script>
            (function (i, s, o, g, r, a, m) {
                i['GoogleAnalyticsObject'] = r;
                i[r] = i[r] || function () {
                    (i[r].q = i[r].q || []).push(arguments)
                },
                i[r].l = 1 * new Date();
                a = s.createElement(o),
                m = s.getElementsByTagName(o)[0];
                a.async = 1;
                a.src = g;
                m.parentNode.insertBefore(a, m)
            })(window, document, 'script', 'https://www.google-analytics.com/analytics.js', 'ga');

            ga('create', 'UA-89110215-1', 'auto');
            ga('send', 'pageview');
        </script>
    </head>

    <body>
        <!-- HEADER -->
        <%= render 'layouts/header' %>

        <!-- BODY -->
        <% flash.each do |message_type, message| %>
        <div class="<%= message_type %> callout" data-closable>
            <%= message %>
            <button class="close-button" aria-label="Dismiss alert" type="button" data-close>
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
        <% end %>
        <%= yield %>

        <!-- FOOTER -->
        <%= render 'layouts/footer' %>
        <%= debug(params) if Rails.env.development? %>
    </body>
</html>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
<div id="error_explanation">
    <div class="alert alert-danger">
        The form contains
        <%= pluralize(@user.errors.count, "error") %>.
    </div>
    <ul>
        <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
        <% end %>
    </ul>
</div>
<% end %>